### ISSUE TITLE
Example spring context files + spring security

### ISSUE THREAD

**Issue by ghost** [Fallwizard/Fallwizard#9]
Hi,

Do you have some examples of context files for spring please ? I could not see in your source. I am trying to integrate spring security @0.7 version currently.

Paul

**Comment by jar349** [comment]
Here's an example of the fallwizard config yml that we've used in the past.

``` yaml
applicationContext: ['config/ldapUserDetailsContext.xml', 'config/applicationContext.xml', 'config/x509AuthSecurityContext.xml']

useSpringSecurity: true

logging:
    level: DEBUG
    loggers:
        "org.springframework.core.env.StandardEnvironment": INFO
        "org.eclipse.jetty.util.component.AbstractLifeCycle": INFO
        "org.eclipse.jetty.util.component.Container": INFO
        "org.eclipse.jetty.server.handler.AbstractHandler": INFO
        "org.eclipse.jetty.servlet.ServletHandler": INFO
        "org.springframework.beans.factory.support.DefaultListableBeanFactory": INFO
        "org.springframework.beans.factory.xml": INFO
        "org.eclipse.jetty.io.nio.ssl": INFO
        "org.eclipse.jetty.io": INFO
        "org.eclipse.jetty.http": INFO
        "org.eclipse.jetty.server.AsyncHttpConnection": INFO
        "org.eclipse.jetty.server.handler": INFO
        "org.eclipse.jetty.server.session": INFO
        "org.springframework.security.web.context": INFO
    console:
        enabled: true
        threshold: DEBUG
    file:
        enabled: true
        threshold: ALL
        currentLogFilename: ./logs/api.log
        archivedLogFilenamePattern: ./logs/api-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC


http:
    connectorType: nonblocking+ssl
    ssl:
        keyStore: ./keys/keystore.jks
        keyStorePassword: "password"
        trustStore: ./keys/truststore.jks
        trustStorePassword: "password"
        wantClientAuth: true
        needClientAuth: false
    port: 15678
    adminPort: 8082
    adminUsername: admin
    adminPassword: admin
    rootPath: /api/*

```

and here's the application context file where we configure spring security:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:c="http://www.springframework.org/schema/c"
       xmlns:sec="http://www.springframework.org/schema/security"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security-3.1.xsd">


    <sec:http use-expressions="true">
        <sec:x509 subject-principal-regex="(.*)" />
        <sec:intercept-url pattern="/api/identity/**" access="hasRole('Domain Users')" />
        <sec:intercept-url pattern="/api/admin/**" access="hasRole('API Admins')" />
        <sec:intercept-url pattern="/api/**" access="permitAll" />
    </sec:http>

    <sec:authentication-manager>
        <sec:authentication-provider user-service-ref="ldapUserDetailsService" />
    </sec:authentication-manager>


</beans>
```
